- Dockerfile
> Bump container version to 1.21 to resolve vulnerabilities

- Dockerfile
Bump helm-operator image to 1.22.0 to resolve the high security alerts
> Bump helm-operator image to 1.22.0

- README.md
Fix broken link (missing .md)
- [X ] I have checked that all unit tests pass after adding my changes
> fix: broken link for upgrades

- Dockerfile
- Makefile
- bundle.Dockerfile
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
Updates SDK to `v1.23.0`
Supersedes #34
> Update Operator SDK to v1.23.0

- CHANGELOG.md
- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator-nginx-ingress-admin_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
Docs, version, and bundle updates for v1.2.0
> Release v1.2.0

- CHANGELOG.md
- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 1.2.1

- docs/manual-installation.md
- docs/openshift-installation.md
> Fix incorrect kubectl commands

- Dockerfile
Updates packages in the base image that have CVEs
> Update packages for CVEs

- CHANGELOG.md
- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
Update docs for 1.3.0 and run make bundle
> Release 1.3.0

- CHANGELOG.md
- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Update docs for v1.3.1

- Dockerfile
Fixes https://github.com/nginxinc/nginx-ingress-helm-operator/security/code-scanning/204
> Update package for CVE-2022-47629

- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- config/samples/charts_v1alpha1_nginxingress.yaml
- helm-charts/nginx-ingress/Chart.yaml
- helm-charts/nginx-ingress/README.md
- helm-charts/nginx-ingress/crds/appprotectdos.f5.com_dosprotectedresources.yaml
- helm-charts/nginx-ingress/crds/externaldns.nginx.org_dnsendpoints.yaml
- helm-charts/nginx-ingress/crds/k8s.nginx.org_globalconfigurations.yaml
- helm-charts/nginx-ingress/crds/k8s.nginx.org_policies.yaml
- helm-charts/nginx-ingress/crds/k8s.nginx.org_transportservers.yaml
- helm-charts/nginx-ingress/crds/k8s.nginx.org_virtualserverroutes.yaml
- helm-charts/nginx-ingress/crds/k8s.nginx.org_virtualservers.yaml
- helm-charts/nginx-ingress/values-icp.yaml
- helm-charts/nginx-ingress/values-plus.yaml
- helm-charts/nginx-ingress/values.schema.json
- helm-charts/nginx-ingress/values.yaml
> Update for nic 3.0.2

- CHANGELOG.md
- Makefile
- README.md
- bundle.Dockerfile
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 1.3.1

- docs/openshift-installation.md
Closes https://github.com/nginxinc/nginx-ingress-helm-operator/issues/89
> Update operator capabilities link

- CHANGELOG.md
- Makefile
- README.md
- bundle.Dockerfile
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
Updates to helm operator for Ingress Controller v3.1.0
> Release 1.4.0

- resources/scc.yaml
Fix the SCC to reflect changes in NGINX Ingress Controller v3.1.0. 
See https://github.com/nginxinc/kubernetes-ingress/pull/3629/files and https://github.com/nginxinc/kubernetes-ingress/pull/3573/files
> fix: update SCC

- CHANGELOG.md
- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 1.4.1

- helm-charts/nginx-ingress/templates/rbac.yaml
> Fix ClusterRole name

- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- hack/get_image_info.sh
> Switch to quay.io

- CHANGELOG.md
- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 1.4.2

- resources/scc-daemonset.yaml
- resources/scc.yaml
Fixes https://github.com/nginxinc/nginx-ingress-helm-operator/issues/116
> Update scc.yaml and scc-daemonset.yaml

- .github/workflows/sync-chart.yml
The GitHub user doesn't tigger workflows, using our bot account fixes this.
> Use nginx-bot to commit changes

- .github/workflows/ci.yml
Adds steps to submit the new Docker images for certification, on a tag event.
> Add steps to submit images for certification

- Makefile
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- hack/get_image_info.sh
Updates to use `quay.io` in the `Makefile` and generate files correctly
> Update to quay.io in Makefile

- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 1.5.2

- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 2.0.1

- Makefile
- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 2.0.2

- .github/workflows/ci.yml
Adds a missing checkout step in the workflow
> Add missing step in certify job

- .github/workflows/sync-chart.yml
Updates the script for the new directory structure and to prevent the schema folder for being deleted.
> Update sync script with new directory structure

- .github/workflows/ci.yml
Fix for deprecated 1.8.0 version of preflight tool
> bump preflight to version 1.9.1

- Makefile
- bundle.Dockerfile
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/rbac/auth_proxy_service.yaml
Address issues in operator certification
> bump minimum openshift version to 4.12

- .github/labeler.yml
- config/crd/kustomization.yaml
- config/default/kustomization.yaml
Kustomization was giving alerts about deprecated syntax.
Address labeler issue.
> address kustomization deprecation warnings

- docs/upgrades.md
> fix: a typo and remove alias references to kubectl

- README.md
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml
- docs/manual-installation.md
- docs/openshift-installation.md
> Release 2.2.1

- .github/workflows/ci.yml
bump preflight version to 1.9.4
> bump preflight version to 1.9.4

- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> correct operator version 2.2.1

- Makefile
- docs/upgrades.md
> makefile fix

- bundle/manifests/nginx-ingress-operator-nginx-ingress-admin_rbac.authorization.k8s.io_v1_clusterrole.yaml
- Update operator bundle manifest
> update bundle clusterrole manifest

- .github/workflows/sync-chart.yml
fix typo in role binding template name
> fix typo in role binding template name

- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- Update to latest release of [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy), v0.18.0. 
- Pull from maintainers registry
> update rbac proxy to v.0.18.0

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/dependabot-auto-merge.yml
- add workflow for dependabot PR's to auto-merge
- update PR template to reference `main` rather than `master` branch
> dependabot auto merge

- docs/manual-installation.md
Update installation docs to include line break on setting the `IMAGE_PULL_SECRET` variable note
> add line break to installation docs

- .github/workflows/f5-cla.yml
- CONTRIBUTING.md
> Add CLA bot workflow

- .github/workflows/ci.yml
Bump preflight version from `1.9.4`, to `1.9.9`
https://github.com/nginxinc/nginx-ingress-helm-operator/actions/runs/11107625697/job/30858750485
> bump preflight to 1.9.9

- .github/workflows/ci.yml
- Makefile
- bundle.Dockerfile
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
update preflight & operator sdk versions
> update preflight & operator sdk versions

- .github/workflows/ci.yml
- bundle/manifests/nginx-ingress-operator-nginx-ingress-admin_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role.yaml
- Update roles to clusterroles to facilitate lease management
- Update IC roles for prod telemetry 
> update clusterrole and roles

- bundle/manifests/nginx-ingress-operator-nginx-ingress-admin_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
Give operator node list permissions for telemetry
> update node permissions

- .github/workflows/sync-chart.yml
Only checkout the required directory.
> Add sparse-checkout to kubernetes-json-schema checkout

- .github/workflows/e2e-test.yml
- update regex to get latest supported k8s version form minikube release notes
- update regex to get latest minikube version
> update regex to get version form minikube release notes

- .github/workflows/ci.yml
Bump preflight version to v1.14.1
> Bump preflight version to v1.14.1
