.github/release-drafter.yml, Dockerfile, Makefile, README.md, bundle.Dockerfile, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, docs/installation.md, docs/manual-installation.md, docs/openshift-installation.md, examples/deployment-oss-min/README.md, examples/deployment-plus-min/README.md
- Updates SDK to 1.22.2
- Updates to `v1.1.0` in all the places
- Fixes typos
=> Update Operator SDK to v1.22.2

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
- Updated references of the Operator SDK with the latest version https://github.com/operator-framework/operator-sdk/releases/tag/v1.24.0
- Ran `make bundle` to update the generated files
=> Update Operator SDK to v1.24.0

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
Bumps the SDK to https://github.com/operator-framework/operator-sdk/releases/tag/v1.25.1
=> Update Operator SDK to v1.25.1

bundle.Dockerfile
The Operator Bundle certification fails with any version < 4.8 with a message that says they've reached its end of life
=> Update supported OpenShift version

.github/workflows/ci.yml, .github/workflows/notifications.yml, Dockerfile
- Adds Quay.io
- Removes updated notification job, creates new notification workflow
- Adds Docker labels to CI
=> Update CI workflow

Makefile, bundle.Dockerfile, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
Bumps the SDK to `1.26` in the rest of the codebase.
=> Bump operator-sdk to 1.26

bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Due to the Helm Operator's caching behaviour, increase the memory limit of the operator to reduce the occurrence of `OOMkilled` events
=> Increase operator memory limit

docs/installation.md
Add documentation to advise users to watch single namespace or increase memory limit in case of an `OOMkill` event
=> Add documentation for Helm Operator OOM issue

Dockerfile
Updates `libxml2` for `CVE-2022-40303`
=> Update package for CVE-2022-40303

CHANGELOG.md, Makefile, README.md, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml, docs/manual-installation.md, docs/openshift-installation.md
This reverts commit 1204446474ce552c718de778dc6a35d09f5fdb76. 
We don't require an image built without the provenance flag - as it turns out, it did not fix our issue on certification.
Reverting this docs bump and deleting the new tag and images.
=> Revert "Update docs for v1.3.1 (#72)"

.github/workflows/ci.yml, .github/workflows/dockerhub-description.yml, .github/workflows/labeler.yml, .github/workflows/notifications.yml, .github/workflows/stale.yml
`contents: write` is needed for the action to create/update the release draft
=> Fix CI workflow permissions

CHANGELOG.md, Makefile, README.md, bundle.Dockerfile, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/kustomization.yaml, config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml, docs/manual-installation.md, docs/openshift-installation.md, docs/upgrades.md
- Updates docs and tags to `1.5.0`
- Bumps min version of OpenShift to v4.10 (v4.9 is deprecated)
- Bumps `ose-kube-rbac-proxy` to `v4.13`
- Fixes `minKubeVersion` that should've been `1.22` already
=> Release 1.5.0

Makefile, README.md, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml, docs/manual-installation.md, docs/openshift-installation.md, docs/upgrades.md
=> Release 1.5.1

helm-charts/nginx-ingress/values.schema.json
Fixes the path to the schema files
Fixes #158 
Fixes #159
=> Fix Helm Schema path

.github/workflows/sync-chart.yml
Adds steps to install the latest version of Helm. This will help us avoid getting stuck on a version from https://github.com/actions/runner-images that has bugs.
=> Add Helm setup step

.github/workflows/pr-certified.yml
Adds automation to open a PR to certify the Operator
=> Add workflow to automate PR creation in certified-operators

.github/workflows/ci.yml
operator version was being incorrectly supplied as `vv2.1.0`
=> remove leading `v` from operator PR

docs/manual-installation.md, docs/openshift-installation.md, docs/upgrades.md
- Update docs to include CRD upgrade
=> Update docs to include CRD upgrade

Makefile, README.md, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
=> Release 2.1.1

bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, bundle/tests/scorecard/config.yaml, config/manager/manager.yaml, config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
New Pre-requisite annotations for Openshift certification
=> add openshift feature annotations

Makefile, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/manifests/bases/kustomization.yaml, config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml
- allow user to set kube-rbac-proxy image & tag via Makefile variables `KRP_IMAGE_BASE` & `KRP_IMAGE_TAG`
- set `containerImage` value when `VERSION` variable changes
- make it clear which values in the templates are placeholders
- bump minimum kubernetes version to 1.26
=> allow user to set kube-rbac-proxy image

Makefile, docs/manual-installation.md
Add documentation for installing from the operator images (including kube-rbac-proxy) from a private container registry
=> add documentation for using private registry

.github/workflows/sync-chart.yml
- update operator version
- ensure kubernetes json schema is the correct version
- update helm schema file to use local k8s refs
- update bundle manifest files
=> add operator version input to replace

Makefile, docs/manual-installation.md
Add image pull secret name variable to makefile
This will add imagePullSecrets: with a secret name to the deployment.
=> add image pull secret name variable to makefile

.github/workflows/ci.yml, .github/workflows/sync-chart.yml
- `nginx-bot` is not required for sync-chart.yml workflow
- disable automated PR certification process, it will need to be done manually for now.
=> Remove nginx-bot where possible

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, .github/workflows/dependency-review.yml, CHANGELOG.md, CODEOWNERS, CONTRIBUTING.md, PROJECT, README.md, bundle/manifests/nginx-ingress-operator.clusterserviceversion.yaml, config/manifests/bases/nginx-ingress-operator.clusterserviceversion.yaml, docs/manual-installation.md, docs/openshift-installation.md, docs/upgrades.md
Fix  migrating nginxinc to nginx
=> Fix  migrating nginxinc to nginx

.github/workflows/e2e-test.yml
Since Kubernetes v1.34.0 released, Minikube has been failing to start due to not supporting that version.
To fix the tests, it is best to check for latest supported Kubernetes version that minikube uses.
=> Fix Minikube in e2e tests to get latest supported Kubernetes version

bundle/manifests/nginx-ingress-operator-nginx-ingress-admin_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/rbac/role.yaml
Allow more permissions for headless service for zone-sync to work with operator.
=> Allow more permissions for headless service

.github/workflows/ci.yml, .github/workflows/e2e-test.yml, .github/workflows/release-operator.yml
- Change to F5 runners for release builds
- Separate release workflow
- Have e2e tests run against image built
=> Change to F5 runners for release builds

.github/workflows/ci.yml
The task to update the Github release draft is failing due to a lack of permissions.  This PR adds the `content: write` permission to the build job.
=> Update release draft permissions
